POST http://localhost:8080/api/generate/doc
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzd2lsYWgiLCJyb2xlcyI6WyJSb2xlX1VzZXIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2xvZ2luIiwiZXhwIjoxNjI5MTk4Mzg2fQ.oGGjg8ckf15ugY3GTOhT0HmzeHt2Gswx5cmz8x0HWlY

{
  "consultants": [
    {
      "email_RATP": "string",
      "ligne_directe_RATP": 3355344666565,
      "nom": "string0",
      "poste": "string"
    } ,
    {
      "email_RATP": "string",
      "ligne_directe_RATP": 3355344666565,
      "nom": "string1",
      "poste": "string"
    }
 ],
  "date_test": "string",
  "nom_projet": "string",
  "nombre_consultants": 1
}

